// Array of quotes for Aquarius
const dailyInspirations = [
    "Challenge yourself to try something new in the bedroom",
    "Seduce your partner with a surprise evening of passion",
    "Explore your deepest desires and fantasies with your partner",
    // Add more quotes here
    "Ignite the flames of passion with a sexy dance for your partner",
    "Indulge in sensual massages to enhance intimacy with your partner",
    "Spice up your love life with a romantic getaway for just the two of you",
    "Get adventurous and try out new positions to keep things exciting in the bedroom",
    "Surprise your partner with a sexy strip tease to turn up the heat",
    "Take control and be the one to initiate intimacy with your partner",
    "Embrace your wild side and explore new boundaries with your partner",
    "Dare to be bold and act out your wildest fantasies with your partner",
    "Create a sexy scavenger hunt leading to a night of passion with your partner",
    "Don't be afraid to talk dirty and express your deepest desires to your partner",
    "Inject some excitement into your relationship by trying out role-playing scenarios",
    "Experiment with different toys and accessories to enhance your sexual experience",
    "Explore the world of erotica and find inspiration for new ways to pleasure your partner",
    "Transform your bedroom into a sensual oasis with candles, music, and seductive decor",
    "Take the time to pamper yourself and boost your confidence for a night of passion",
    "Don't be afraid to take the lead and show your partner what you desire",
    "Get creative and write your partner a steamy love letter to express your desires",
    "Keep the spark alive by surprising your partner with unexpected acts of passion",
    "Dress up in sexy lingerie and treat your partner to a night they'll never forget",
    "Use your imagination and create your own sexy games to play with your partner",
    "Share your deepest fantasies with your partner and explore them together",
    "Show your partner how much you desire them with passionate kisses and caresses",
    "Take the time to set the mood with romantic gestures and thoughtful surprises",
    "Don't be afraid to take risks and push the boundaries of your comfort zone",
    "Make time for intimacy and prioritize your connection with your partner",
    "Communicate openly and honestly with your partner about your desires and needs",
    "Invest in your relationship by making time for each other and nurturing your connection",
    "Embrace your sexuality and explore what brings you pleasure without shame or judgment.",
    "Celebrate your body and all its desires, knowing that you are deserving of pleasure.",
    "Give yourself permission to explore your fantasies and desires without guilt or inhibition.",
    "Find empowerment in your sexuality, knowing that it is a natural and beautiful part of who you are.",
    "Express your sexuality in ways that feel authentic and fulfilling to you, regardless of societal norms or expectations.",
    "Create a safe and consensual space for sexual exploration and expression, free from judgment or shame.",
    "Celebrate the diversity of human sexuality, recognizing that there is no one 'right' way to experience pleasure.",
    "Honor your desires and boundaries, knowing that you have the right to say 'yes' or 'no' to any sexual experience.",
    "Explore your sexual identity and preferences, knowing that they may change and evolve over time.",
    "Practice self-love and self-care in your sexual experiences, prioritizing your pleasure and well-being.",
    "Educate yourself about sexual health and safety, empowering yourself to make informed choices.",
    "Advocate for sexual freedom and rights for all individuals, recognizing that everyone deserves the right to express their sexuality freely.",
    "Challenge societal norms and expectations around sexuality, advocating for a more inclusive and accepting culture.",
    "Support and uplift others in their sexual journeys, recognizing that everyone's experiences are valid and valuable.",
    "Celebrate the beauty and diversity of human bodies, embracing your own unique form.",
    "Explore different forms of pleasure beyond traditional notions of sex, finding what brings you joy and fulfillment.",
    "Practice open and honest communication about your sexual desires and boundaries, creating a safe space for intimacy.",
    "Embrace your sensuality and express it in ways that feel authentic and empowering to you.",
    "Seek out resources and communities that support sexual freedom and exploration, finding a supportive network of like-minded individuals.",
    "Challenge stereotypes and stigma around sexuality, recognizing that everyone's experiences are valid and deserving of respect.",
    "Celebrate your sexual victories, no matter how big or small, knowing that each step forward is worth honoring.",
    "Find joy in your sexual experiences, knowing that pleasure is a natural and essential part of life.",
    "Practice mindfulness in your sexual experiences, staying present and attuned to your body's sensations.",
    "Embrace your sexual desires and fantasies, knowing that they are a natural and healthy part of who you are.",
    "Express gratitude for the pleasure and intimacy you experience, savoring each moment of connection.",
    "Release any shame or guilt around your sexual experiences, knowing that you are deserving of pleasure and joy.",
    "Connect with your body and its desires, listening to its cues and honoring its needs.",
    "Create a sacred space for sexual exploration and expression, honoring the divine within yourself and others.",
    "Celebrate your sexuality as a powerful and transformative force, capable of bringing you joy and fulfillment.",
    "Find inspiration in the beauty and wonder of the natural world, connecting with the primal and sensual aspects of life.",
    "Seek out experiences that bring you pleasure and joy, knowing that you deserve to feel good.",
    "Express your sexuality with confidence and self-assurance, knowing that you are worthy of love and pleasure.",
    "Explore your sexual desires and boundaries with curiosity and openness, allowing yourself to discover new and exciting experiences.",
    "Find empowerment in your sexual experiences, knowing that they are a reflection of your inner strength and beauty.",
    "Celebrate your sexual uniqueness, knowing that there is no one else in the world quite like you.",
    "Embrace your sexual desires and fantasies, knowing that they are a natural and healthy expression of your inner self.",
    "Express your sexuality in ways that feel authentic and true to you, without fear of judgment or shame.",
    "Explore different aspects of your sexuality, allowing yourself to discover new and exciting forms of pleasure.",
    "Practice self-love and self-acceptance in your sexual experiences, knowing that you are deserving of pleasure and joy.",
    "Celebrate your sexual desires and fantasies as a natural and healthy expression of your inner self.",
    "Express your sexuality with confidence and self-assurance, knowing that you are worthy of love and pleasure.",
    "Explore your sexual desires and boundaries with curiosity and openness, allowing yourself to discover new and exciting experiences.",
    "Find empowerment in your sexual experiences, knowing that they are a reflection of your inner strength and beauty.",
    "Celebrate your sexual uniqueness, knowing that there is no one else in the world quite like you.",
    "Embrace your sexual desires and fantasies, knowing that they are a natural and healthy expression of your inner self.",
    "Express your sexuality in ways that feel authentic and true to you, without fear of judgment or shame.",
    "Explore different aspects of your sexuality, allowing yourself to discover new and exciting forms of pleasure.",
    "Practice self-love and self-acceptance in your sexual experiences, knowing that you are deserving of pleasure and joy.",
    "Celebrate your sexual desires and fantasies as a natural and healthy expression of your inner self.",
    "Express your sexuality with confidence and self-assurance, knowing that you are worthy of love and pleasure.",
    "Explore your sexual desires and boundaries with curiosity and openness, allowing yourself to discover new and exciting experiences.",
    "Find empowerment in your sexual experiences, knowing that they are a reflection of your inner strength and beauty.",
    "Celebrate your sexual uniqueness, knowing that there is no one else in the world quite like you.",
    "Embrace your sexual desires and fantasies, knowing that they are a natural and healthy expression of your inner self.",
    "Express your sexuality in ways that feel authentic and true to you, without fear of judgment or shame.",
    "Explore different aspects of your sexuality, allowing yourself to discover new and exciting forms of pleasure.",
    "Practice self-love and self-acceptance in your sexual experiences, knowing that you are deserving of pleasure and joy.",
    "Celebrate your sexual desires and fantasies as a natural and healthy expression of your inner self.",
    "Express your sexuality with confidence and self-assurance, knowing that you are worthy of love and pleasure.",
    "Explore your sexual desires and boundaries with curiosity and openness, allowing yourself to discover new and exciting experiences.",
    "Find empowerment in your sexual experiences, knowing that they are a reflection of your inner strength and beauty.",
    "Celebrate your sexual uniqueness, knowing that there is no one else in the world quite like you.",
    "Embrace your sexual desires and fantasies, knowing that they are a natural and healthy expression of your inner self.",
    "Express your sexuality in ways that feel authentic and true to you, without fear of judgment or shame.",
    "Explore different aspects of your sexuality, allowing yourself to discover new and exciting forms of pleasure.",
    "Practice self-love and self-acceptance in your sexual experiences, knowing that you are deserving of pleasure and joy.",
    "Celebrate your sexual desires and fantasies as a natural and healthy expression of your inner self.",
    "Express your sexuality with confidence and self-assurance, knowing that you are worthy of love and pleasure.",
    "Explore your sexual desires and boundaries with curiosity and openness, allowing yourself to discover new and exciting experiences.",
    "Send a sexy text message to your partner right now.",
    "Try a new position you've never done before.",
    "Role-play a fantasy scenario with your partner.",
    "Watch an erotic movie together and explore your desires.",
    "Experiment with a new sex toy or accessory.",
    "Have a steamy make-out session in an unexpected place.",
    "Write down your wildest sexual fantasy and share it with your partner.",
    "Give your partner a sensual massage and explore their body.",
    "Have a naked dance party with your partner.",
    "Take a sensual shower or bath together.",
    "Sensuality is about enjoying every sensation, every touch, every moment of pleasure.",
    "Let your body be the canvas, and let pleasure be your masterpiece.",
    "In the dance of love, let passion be your guide.",
    "Embrace the sensuality of the moment, and let it take you to new heights of pleasure.",
    "Savor every touch, every kiss, and let them ignite the fire of desire within you.",
    "The art of seduction lies in the subtle dance of anticipation and fulfillment.",
    "Explore the depths of pleasure, and let your senses be your guide.",
    "In the game of love, let desire be your strategy and passion be your prize.",
    "Let your body speak the language of love, and let passion be your voice.",
    "In the symphony of pleasure, let your body be the instrument, and let desire be the music.",
    "The path to ecstasy is paved with the delicate touch of passion and desire.",
    "Let your senses be your guide, and let the journey of pleasure begin.",
    "Sensuality is not just about the body, but about the mind and soul as well.",
    "In the realm of pleasure, let your imagination run wild, and let desire be your compass.",
    "Let your body be the temple of pleasure, and let passion be your worship.",
    "The art of seduction is not in the destination, but in the journey of pleasure.",
    "Let every touch be a caress, every kiss a promise, and every moment a memory.",
    "Sensuality is the key to unlocking the door to pleasure, so let yourself be immersed in its beauty.",
    "In the dance of desire, let your body be the muse, and let passion be the artist.",
    "Explore the boundaries of pleasure, and let your senses be your guide.",
    "Sensuality is not a destination, but a journey of exploration and discovery.",
    "Let your body be a playground of pleasure, and let passion be your guide.",
    "In the realm of sensuality, let your desires run free, and let pleasure be your reward.",
    "Savor the taste of passion, and let it linger on your lips like the sweetest nectar.",
    "Let every touch be a whisper of desire, and let every kiss be a promise of ecstasy.",
    "In the game of love, let desire be your weapon, and let passion be your shield.",
    "Explore the depths of pleasure, and let your senses be your guide.",
    "Sensuality is not just about the body, but about the mind and soul as well.",
    "In the realm of pleasure, let your imagination run wild, and let desire be your compass.",
    "Let your body be the temple of pleasure, and let passion be your worship.",
    "The art of seduction is not in the destination, but in the journey of pleasure.",
    "Let every touch be a caress, every kiss a promise, and every moment a memory.",
    "Sensuality is the key to unlocking the door to pleasure, so let yourself be immersed in its beauty.",
    "In the dance of desire, let your body be the muse, and let passion be the artist.",
    "Explore the boundaries of pleasure, and let your senses be your guide.",
    "Sensuality is not a destination, but a journey of exploration and discovery.",
    "Let your body be a playground of pleasure, and let passion be your guide.",
    "In the realm of sensuality, let your desires run free, and let pleasure be your reward.",
    "Savor the taste of passion, and let it linger on your lips like the sweetest nectar.",
    "Let every touch be a whisper of desire, and let every kiss be a promise of ecstasy.",
    "In the game of love, let desire be your weapon, and let passion be your shield.",
    "Explore the depths of pleasure, and let your senses be your guide.",
    "Sensuality is not just about the body, but about the mind and soul as well.",
    "In the realm of pleasure, let your imagination run wild, and let desire be your compass.",
    "Let your body be the temple of pleasure, and let passion be your worship.",
    "The art of seduction is not in the destination, but in the journey of pleasure.",
    "Let every touch be a caress, every kiss a promise, and every moment a memory.",
    "Sensuality is the key to unlocking the door to pleasure, so let yourself be immersed in its beauty.",
    "In the dance of desire, let your body be the muse, and let passion be the artist.",
    "Explore the boundaries of pleasure, and let your senses be your guide.",
    "Sensuality is not a destination, but a journey of exploration and discovery.",
    "Let your body be a playground of pleasure, and let passion be your guide.",
    "In the realm of sensuality, let your desires run free, and let pleasure be your reward."
];

const kinkyQuotes = [
    "The only way to get rid of a temptation is to yield to it. Resist it, and your soul grows sick with longing for the things it has forbidden to itself.",
    "I'm not a slave to your desires, I'm the master of them.",
    "Try a new sex position you've never done before.",
    "Have sex in a different room of the house.",
    "Use a blindfold or handcuffs during sex.",
    "Role play a fantasy scenario with your partner.",
    "Have sex in a public place (safely and discreetly).",
    "Experiment with a sex toy or vibrator.",
    "Watch porn together and act out a scene.",
    "Have a quickie in an unexpected place.",
    "Write a sexual fantasy and share it with your partner.",
    "Take a sexy photo or video for your partner.",
    "Explore anal play (safely and with consent).",
    "Try mutual masturbation with your partner.",
    "Have sex outdoors under the stars.",
    "Take a bath or shower together and explore each other's bodies.",
    "Try a new kink or fetish that interests you both.",
    "Plan a romantic evening with candles, music, and seduction.",
    "Give your partner a sensual massage.",
    "Explore edging or orgasm control with your partner.",
    "Experiment with dirty talk and verbal seduction.",
    "Attend a sex workshop or seminar together.",
    "Visit a sex shop and pick out a new toy or accessory together.",
    "Try a new lubricant or massage oil for added pleasure.",
    "Have sex in the morning before starting your day.",
    "Send your partner a sexy text message or voice note.",
    "Watch an erotic movie or read erotica together.",
    "Experiment with temperature play using ice or warm oil.",
    "Try a new role or persona in bed.",
    "Explore bondage or restraints with your partner.",
    "Have sex with the lights on for a change.",
    "Try a new oral sex technique on your partner.",
    "Create a sexual bucket list together and start checking things off.",
    "Have a naked day at home where clothes are optional.",
    "Role play a first-time encounter with your partner.",
    "Use food or edible items in your sexual play.",
    "Try a new location for sex, like the kitchen counter or dining table.",
    "Have a themed dress-up night where you both dress up in costumes.",
    "Explore tantric sex techniques for a deeper connection.",
    "Try a new sensation play activity, like using feathers or silk.",
    "Share a sexual fantasy and act it out together.",
    "Experiment with different forms of orgasm, like G-spot or clitoral orgasms.",
    "Have sex in the shower or bath for a slippery and sensual experience.",
    "Try a new position from the Kama Sutra or another sex guide.",
    "Role play a scenario where one of you is the teacher and the other is the student.",
    "Try a sexual challenge, like seeing how many orgasms you can give each other in a set time.",
    "Experiment with erotic hypnosis for a unique sexual experience.",
    "Try a new form of sexual communication, like writing erotica or drawing erotic art.",
    "Explore sensory deprivation with a blindfold and earplugs.",
    "Try a new sexual game or app designed for couples.",
    "Role play a scenario where one of you is a famous person and the other is a fan.",
    "Have sex in a tent or camping setting for a wild and adventurous experience.",
    "Try a new technique for prolonged foreplay and build anticipation.",
    "Explore mutual masturbation over video chat for a long-distance thrill.",
    "Have sex during a thunderstorm for added atmosphere.",
    "Try a new form of orgasm control, like edging or denial.",
    "Role play a scenario where one of you is a vampire and the other is their prey.",
    "Experiment with a new form of erotic massage, like Nuru massage.",
    "Try a new type of sexual role, like dominant/submissive or switch roles.",
    "Have sex in a car or other tight space for a thrilling experience.",
    "Explore a new form of bondage or restraint, like Shibari.",
    "Try a new form of erotic dance, like pole dancing or belly dancing.",
    "Have sex while listening to a guided meditation for a mindful experience.",
    "Experiment with a new form of sensation play, like using feathers or ice.",
    "Try a new sexual technique, like extended foreplay or multiple orgasms.",
    "Role play a scenario where one of you is a superhero and the other is their sidekick.",
    "Have sex during a full moon for a mystical experience.",
    "Try a new form of erotic storytelling, like writing a dirty story together.",
    "Experiment with a new form of erotic art, like nude photography or body painting.",
    "Try a new form of sexual meditation, like tantric breathing exercises.",
    "Role play a scenario where one of you is a mermaid/man and the other is a sailor.",
    "Have sex in a hammock or other swinging furniture for a fun and bouncy experience.",
    "Explore a new form of erotic literature, like reading aloud to each other.",
    "Try a new form of sexual communication, like writing love letters or sexting.",
    "Experiment with a new form of erotic role, like a doctor/patient or boss/employee.",
    "Try a new form of sexual challenge, like seeing how many orgasms you can have in a day.",
    "Role play a scenario where one of you is a time traveler and the other is a historical figure.",
    "Have sex in a sauna or steam room for a hot and steamy experience.",
    "Try a new form of erotic dance, like tango or salsa.",
    "Explore a new form of sexual game, like truth or dare or strip poker.",
    "Try a new form of erotic performance, like burlesque or drag.",
    "Experiment with a new form of sexual meditation, like guided visualization.",
    "Role play a scenario where one of you is a fairy and the other is a human.",
    "Have sex on a boat or ship for a nautical adventure.",
    "Try a new form of sexual role, like teacher/student or boss/secretary.",
    "Explore a new form of erotic massage, like Thai or hot stone massage.",
    "Try a new form of sexual communication, like writing love poems or sharing fantasies.",
    "Experiment with a new form of erotic art, like painting or sculpture.",
    "Try a new form of sexual challenge, like a sex marathon or orgasm competition.",
    "Role play a scenario where one of you is an alien and the other is an earthling.",
    "Have sex in a hot tub or Jacuzzi for a bubbly experience.",
    "Try a new form of erotic storytelling, like improvisational storytelling.",
    "Explore a new form of erotic literature, like fan fiction or historical romance.",
    "Try a new form of sexual meditation, like mindful masturbation.",
    "Role play a scenario where one of you is a ghost and the other is a living person.",
    "Have sex in a pool or other body of water for a wet and wild experience.",
    "Try a new form of erotic dance, like ballet or modern dance.",
    "Explore a new form of sexual game, like role-playing games or board games with a sexy twist.",
    "Try a new form of erotic performance, like stand-up comedy or storytelling.",
    "I'm not shy, I'm just holding back my wild side for the right person.",
    "The pleasure is all mine... and hopefully soon, all yours.",
    "I'm not into bondage, but I wouldn't mind being tied up by you.",
    "I'll be your naughty little secret.",
    "Let's make a deal: I'll give you what you crave if you give me what I desire.",
    "I don't need a safe word, I need more of you.",
    "I'm not a dominatrix, but I could play one for you.",
    "I want to explore your every fantasy and make them a reality.",
    "I'm not afraid of a little pain if it comes with a lot of pleasure.",
    "I'm not just a tease, I'm a temptation.",
    "I don't need a knight in shining armor, I need a man in leather.",
    "I'll be your naughty little secret.",
    "I don't need a safe word, I need more of you.",
    "I'm not a dominatrix, but I could play one for you.",
    "I want to explore your every fantasy and make them a reality.",
    "I'm not afraid of a little pain if it comes with a lot of pleasure.",
    "I'm not just a tease, I'm a temptation.",
    "I don't need a knight in shining armor, I need a man in leather.",
    "I don't need a prince charming, I need a man who can handle me at my worst and dominate me at my best.",
    "I'm not asking you to love me, I'm asking you to be my next mistake.",
    "I'm not a one-night stand, I'm a once-in-a-lifetime experience.",
    "I don't need a happily ever after, I just need a happily ever now.",
    "I don't need a fairy tale ending, I need a happily ever after party.",
    "I don't need a fairy godmother, I need a daddy dom.",
    "I'm not looking for a knight in shining armor, I'm looking for a man in leather.",
    "I'm not a damsel in distress, I'm a princess in a latex dress.",
    "I'm not a princess waiting for her prince charming, I'm a queen looking for her king.",
    "I don't need a knight in shining armor, I need a man in leather.",
    "I'm not a damsel in distress, I'm a princess in a latex dress.",
    "I'm not a princess waiting for her prince charming, I'm a queen looking for her king.",
    "I don't need a glass slipper, I need a leather boot.",
    "I don't need a prince charming, I need a man who can handle me at my worst and dominate me at my best.",
    "I'm not asking you to love me, I'm asking you to be my next mistake.",
    "I'm not a one-night stand, I'm a once-in-a-lifetime experience.",
    "I don't need a happily ever after, I just need a happily ever now.",
    "I don't need a fairy tale ending, I need a happily ever after party.",
    "I don't need a fairy godmother, I need a daddy dom.",
    "I'm not looking for a knight in shining armor, I'm looking for a man in leather.",
    "I'm not a damsel in distress, I'm a princess in a latex dress.",
    "I'm not a princess waiting for her prince charming, I'm a queen looking for her king.",
    "I don't need a knight in shining armor, I need a man in leather.",
    "I'm not a damsel in distress, I'm a princess in a latex dress.",
    "I'm not a princess waiting for her prince charming, I'm a queen looking for her king.",
    "I don't need a glass slipper, I need a leather boot.",
    "Embrace your desires without shame or guilt.",
    "Celebrate your sexuality in all its forms.",
    "Your body, your rules.",
    "Sexuality is a spectrum; explore where you belong.",
    "Break free from societal expectations and norms.",
    "Sexual freedom is empowering; own your sexuality.",
    "Consent is key; respect yourself and others.",
    "Explore, experiment, and enjoy your sexual journey.",
    "Sexual liberation starts with self-acceptance.",
    "Dare to be different; dare to be sexually free.",
    "Send a sexy text message to your partner describing what you want to do to them later.",
    "Surprise your partner by wearing lingerie under your clothes and revealing it at an unexpected moment.",
    "Initiate sex in a new location in your home that you've never tried before.",
    "Try a new sexual position that you've never tried before.",
    "Experiment with light bondage, using items you have around the house like scarves or ties.",
    "Plan a sensual massage for your partner, focusing on their pleasure and relaxation.",
    "Watch an erotic movie together and try to recreate one of the scenes.",
    "Play a strip game, like strip poker or strip dice, where the loser removes an article of clothing.",
    "Write down your deepest sexual fantasy and share it with your partner.",
    "Experiment with role-playing, taking on different personas and scenarios to spice up your sex life.",
    "Engage in mutual masturbation, where you pleasure yourselves in front of each other.",
    "Explore erotic literature together and act out a scene from a book.",
    "Try using a sex toy together, choosing one that you both find intriguing.",
    "Have a quickie in a location where you might get caught, like a parked car or a secluded area outdoors.",
    "Experiment with temperature play, using ice cubes or warm oils to heighten sensation.",
    "Engage in a steamy make-out session, focusing on building anticipation and desire.",
    "Take a sexy shower together, exploring each other's bodies under the warm water.",
    "Play a game of truth or dare with a sexual twist, daring each other to perform erotic acts.",
    "Experiment with sensory deprivation, using blindfolds or earplugs to heighten other senses.",
    "Try out a new sexual technique or trick that you've read about or seen online.",
    "Engage in a round of dirty talk, describing your fantasies and desires to each other.",
    "Have a marathon sex session, taking your time to explore each other's bodies and pleasure zones.",
    "Explore a new erogenous zone on your partner's body, giving them pleasure in a new way.",
    "Try out a new lubricant or massage oil, adding a new sensation to your sexual experience.",
    "Engage in some light BDSM play, incorporating elements of dominance and submission into your sex life.",
    "Experiment with edging, bringing each other to the brink of orgasm and then stopping before continuing.",
    "Have sex in a different room in your home, like the kitchen counter or the living room couch.",
    "Try out a new sexual position from the Kama Sutra or another sex manual.",
    "Engage in some role reversal, letting your partner take the lead in the bedroom.",
    "Experiment with a new form of stimulation, like using a feather or a vibrator on each other.",
    "Take turns giving each other sensual massages, focusing on relaxation and pleasure.",
    "Engage in some playful spanking, exploring light BDSM play with your partner.",
    "Try out a new fantasy scenario, like pretending to be strangers meeting for the first time.",
    "Play a game of sexual dice, where each roll corresponds to a different sexual act.",
    "Experiment with erotic food play, using items like whipped cream or chocolate sauce.",
    "Engage in some mutual oral sex, pleasuring each other with your mouths.",
    "Try out a new role-playing scenario, like doctor and patient or teacher and student.",
    "Experiment with a new form of sensation play, like using a feather or a soft brush on each other's skin.",
    "Engage in some erotic wrestling, playfully struggling with each other before succumbing to passion.",
    "Try out a new sex toy together, like a vibrating cock ring or a remote-controlled vibrator.",
    "Have sex in a different position than your usual go-to, exploring new ways to pleasure each other.",
    "Experiment with some light bondage, using restraints to enhance your play.",
    "Try out a new form of sensory play, like using ice cubes or hot wax on each other's skin.",
    "Engage in some erotic storytelling, taking turns describing your fantasies to each other.",
    "Try out a new form of role-playing, like pretending to be strangers meeting for the first time.",
    "Experiment with some light domination and submission play, taking turns being in control.",
    "Try out a new form of temperature play, like using ice cubes or warm oils on each other's skin.",
    "Engage in some mutual masturbation, pleasuring yourselves in front of each other.",
    "Try out a new sexual position, exploring different ways to pleasure each other.",
    "Experiment with some light bondage, using restraints to enhance your play.",
    "Try out a new form of sensation play, like using a feather or a soft brush on each other's skin.",
    "Engage in some erotic wrestling, playfully struggling with each other before succumbing to passion.",
    "Try out a new sex toy together, like a vibrating cock ring or a remote-controlled vibrator.",
    "Have sex in a different position than your usual go-to, exploring new ways to pleasure each other.",
    "Experiment with some light bondage, using restraints to enhance your play.",
    "Try out a new form of sensory play, like using ice cubes or hot wax on each other's skin.",
    "Engage in some erotic storytelling, taking turns describing your fantasies to each other."
];
  



// Function to display a random quote for Aquarius
function displayRandomAquariusQuote() {
    const randomIndex = Math.floor(Math.random() * dailyInspirations.length);
    const quoteElement = document.getElementById("quote");
    quoteElement.textContent = dailyInspirations[randomIndex];
}

// Call the function to display a random quote for Aquarius
displayRandomAquariusQuote();


// Function to display a random quote for Aquarius
function GeneralKinky () {
    const randomIndex = Math.floor(Math.random() * kinkyQuotes.length);
    const quoteElement = document.getElementById("quoteGeneral");
    quoteElement.textContent = kinkyQuotes[randomIndex];
}

// Call the function to display a random quote for Aquarius
GeneralKinky();



